// ============================================================================
// System Design Patterns - Multi-Module Composite Project
// Structure: System Design Theory + System Design Patterns
// ============================================================================

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
    versionCatalogs {
        create("libs") {
            from(files(settingsDir.resolve("../gradle/libs.versions.toml")))
        }
    }
}

rootProject.name = "system-design-patterns"

// ============================================================================
// SYSTEM DESIGN THEORY (41 topics)
// ============================================================================
include(":system-design-theory:ip")
include(":system-design-theory:osi-model")
include(":system-design-theory:tcp-udp")
include(":system-design-theory:dns")
include(":system-design-theory:load-balancing")
include(":system-design-theory:clustering")
include(":system-design-theory:caching")
include(":system-design-theory:cdn")
include(":system-design-theory:proxy")
include(":system-design-theory:availability")
include(":system-design-theory:scalability")
include(":system-design-theory:storage")
include(":system-design-theory:databases-dbms")
include(":system-design-theory:sql-databases")
include(":system-design-theory:nosql-databases")
include(":system-design-theory:sql-vs-nosql")
include(":system-design-theory:database-replication")
include(":system-design-theory:indexes")
include(":system-design-theory:normalization-denormalization")
include(":system-design-theory:acid-base")
include(":system-design-theory:cap-theorem")
include(":system-design-theory:pacelc-theorem")
include(":system-design-theory:transactions")
include(":system-design-theory:distributed-transactions")
include(":system-design-theory:sharding")
include(":system-design-theory:consistent-hashing")
include(":system-design-theory:database-federation")
include(":system-design-theory:n-tier-architecture")
include(":system-design-theory:message-brokers")
include(":system-design-theory:message-queues")
include(":system-design-theory:publish-subscribe")
include(":system-design-theory:enterprise-service-bus")
include(":system-design-theory:monoliths-microservices")
include(":system-design-theory:event-driven-architecture")
include(":system-design-theory:event-sourcing")
include(":system-design-theory:cqrs")
include(":system-design-theory:api-gateway")
include(":system-design-theory:rest-graphql-grpc")
include(":system-design-theory:long-polling-websockets-sse")
include(":system-design-theory:geohashing-quadtrees")
include(":system-design-theory:circuit-breaker")
include(":system-design-theory:rate-limiting")
include(":system-design-theory:service-discovery")
include(":system-design-theory:sla-slo-sli")
include(":system-design-theory:disaster-recovery")
include(":system-design-theory:vms-containers")
include(":system-design-theory:oauth2-oidc")
include(":system-design-theory:sso")
include(":system-design-theory:ssl-tls-mtls")
include(":system-design-theory:consistency-patterns")
include(":system-design-theory:performance-throughput")
include(":system-design-theory:availability-consistency")

// ============================================================================
// SYSTEM DESIGN PATTERNS
// ============================================================================

// S.O.L.I.D Principles (5)
include(":system-design-pattern:solid-principles:single-responsibility-principle")
include(":system-design-pattern:solid-principles:liskov-substitution-principle")
include(":system-design-pattern:solid-principles:dependency-inversion-principle")
include(":system-design-pattern:solid-principles:interface-segregation-principle")
include(":system-design-pattern:solid-principles:open-close-principle")

// Structural Patterns (31)
include(":system-design-pattern:structural:adapter")
include(":system-design-pattern:structural:bridge")
include(":system-design-pattern:structural:business-delegate")
include(":system-design-pattern:structural:component")
include(":system-design-pattern:structural:composite-entity")
include(":system-design-pattern:structural:composite-view")
include(":system-design-pattern:structural:composite")
include(":system-design-pattern:structural:data-access-object")
include(":system-design-pattern:structural:data-transfer-object")
include(":system-design-pattern:structural:converter")
include(":system-design-pattern:structural:curiously-recurring-template-pattern")
include(":system-design-pattern:structural:decorator")
include(":system-design-pattern:structural:domain-model")
include(":system-design-pattern:structural:dynamic-proxy")
include(":system-design-pattern:structural:extension-objects")
include(":system-design-pattern:structural:facade")
include(":system-design-pattern:structural:flyweight")
include(":system-design-pattern:structural:marker-interface")
include(":system-design-pattern:structural:parameter-object")
include(":system-design-pattern:structural:private-class-data")
include(":system-design-pattern:structural:proxy")
include(":system-design-pattern:structural:role-object")
include(":system-design-pattern:structural:separated-interface")
include(":system-design-pattern:structural:servant")
include(":system-design-pattern:structural:service-locator")
include(":system-design-pattern:structural:spatial-partition")
include(":system-design-pattern:structural:special-case")
include(":system-design-pattern:structural:strangler")
include(":system-design-pattern:structural:twin")
include(":system-design-pattern:structural:value-object")
include(":system-design-pattern:structural:virtual-proxy")
include(":system-design-pattern:structural:sidecar")

// Creational Patterns (14)
include(":system-design-pattern:creational:abstract-factory")
include(":system-design-pattern:creational:builder")
include(":system-design-pattern:creational:dependency-injection")
include(":system-design-pattern:creational:factory-kit")
include(":system-design-pattern:creational:factory-method")
include(":system-design-pattern:creational:factory")
include(":system-design-pattern:creational:monostate")
include(":system-design-pattern:creational:multiton")
include(":system-design-pattern:creational:object-pool")
include(":system-design-pattern:creational:prototype")
include(":system-design-pattern:creational:registry")
include(":system-design-pattern:creational:singleton")
include(":system-design-pattern:creational:step-builder")
include(":system-design-pattern:creational:type-object")

// Concurrency Patterns (18)
include(":system-design-pattern:concurrency:active-object")
include(":system-design-pattern:concurrency:async-method-invocation")
include(":system-design-pattern:concurrency:balking")
include(":system-design-pattern:concurrency:double-checked-locking")
include(":system-design-pattern:concurrency:event-based-asynchronous")
include(":system-design-pattern:concurrency:event-queue")
include(":system-design-pattern:concurrency:fan-out-fan-in")
include(":system-design-pattern:concurrency:guarded-suspension")
include(":system-design-pattern:concurrency:half-sync-half-async")
include(":system-design-pattern:concurrency:leader-election")
include(":system-design-pattern:concurrency:leader-followers")
include(":system-design-pattern:concurrency:lockable-object")
include(":system-design-pattern:concurrency:master-worker")
include(":system-design-pattern:concurrency:monitor")
include(":system-design-pattern:concurrency:poison-pill")
include(":system-design-pattern:concurrency:producer-consumer")
include(":system-design-pattern:concurrency:promise")
include(":system-design-pattern:concurrency:reactor")

// Behavioral Patterns (37)
include(":system-design-pattern:behavioral:acyclic-visitor")
include(":system-design-pattern:behavioral:bytecode")
include(":system-design-pattern:behavioral:chain-of-responsibility")
include(":system-design-pattern:behavioral:client-session")
include(":system-design-pattern:behavioral:collecting-parameter")
include(":system-design-pattern:behavioral:command")
include(":system-design-pattern:behavioral:commander")
include(":system-design-pattern:behavioral:context-object")
include(":system-design-pattern:behavioral:data-mapper")
include(":system-design-pattern:behavioral:delegation")
include(":system-design-pattern:behavioral:dirty-flag")
include(":system-design-pattern:behavioral:double-buffer")
include(":system-design-pattern:behavioral:double-dispatch")
include(":system-design-pattern:behavioral:execute-around")
include(":system-design-pattern:behavioral:feature-toggle")
include(":system-design-pattern:behavioral:filterer")
include(":system-design-pattern:behavioral:fluent-interface")
include(":system-design-pattern:behavioral:game-loop")
include(":system-design-pattern:behavioral:health-check")
include(":system-design-pattern:behavioral:identity-map")
include(":system-design-pattern:behavioral:interpreter")
include(":system-design-pattern:behavioral:iterator")
include(":system-design-pattern:behavioral:mediator")
include(":system-design-pattern:behavioral:notification")
include(":system-design-pattern:behavioral:memento")
include(":system-design-pattern:behavioral:mute-idiom")
include(":system-design-pattern:behavioral:null-object")
include(":system-design-pattern:behavioral:observer")
include(":system-design-pattern:behavioral:partial-response")
include(":system-design-pattern:behavioral:pipeline")
include(":system-design-pattern:behavioral:property")
include(":system-design-pattern:behavioral:specification")
include(":system-design-pattern:behavioral:state")
include(":system-design-pattern:behavioral:strategy")
include(":system-design-pattern:behavioral:subclass-sandbox")
include(":system-design-pattern:behavioral:template-method")
include(":system-design-pattern:behavioral:update-method")
include(":system-design-pattern:behavioral:visitor")

// Integration Patterns (3)
include(":system-design-pattern:integration:ambassador")
include(":system-design-pattern:integration:anti-corruption-layer")
include(":system-design-pattern:integration:gateway")

// Microservices Patterns (11)
include(":system-design-pattern:microservices:api-gateway")
include(":system-design-pattern:microservices:service-discovery")
include(":system-design-pattern:microservices:service-registry")
include(":system-design-pattern:microservices:config-server")
include(":system-design-pattern:microservices:log-aggregation")
include(":system-design-pattern:microservices:database-per-service")
include(":system-design-pattern:microservices:service-mesh")
include(":system-design-pattern:microservices:observability")
include(":system-design-pattern:microservices:health-monitoring")
include(":system-design-pattern:microservices:monitoring")
include(":system-design-pattern:microservices:master-service-decomposition")

// Testing Patterns (3)
include(":system-design-pattern:testing:arrange-act-assert")
include(":system-design-pattern:testing:object-mother")
include(":system-design-pattern:testing:page-object")

// Performance Optimization Patterns (3)
include(":system-design-pattern:performance-optimization:caching")
include(":system-design-pattern:performance-optimization:data-locality")
include(":system-design-pattern:performance-optimization:lazy-loading")

// Functional Patterns (7)
include(":system-design-pattern:functional:callback")
include(":system-design-pattern:functional:collection-pipeline")
include(":system-design-pattern:functional:combinator")
include(":system-design-pattern:functional:currying")
include(":system-design-pattern:functional:function-composition")
include(":system-design-pattern:functional:monad")
include(":system-design-pattern:functional:trampoline")

// Resilience Patterns (10)
include(":system-design-pattern:resilience:circuit-breaker")
include(":system-design-pattern:resilience:queue-based-load-leveling")
include(":system-design-pattern:resilience:retry")
include(":system-design-pattern:resilience:saga")
include(":system-design-pattern:resilience:tolerant-reader")
include(":system-design-pattern:resilience:rate-limiting")
include(":system-design-pattern:resilience:bulkheads")
include(":system-design-pattern:resilience:fallbacks")
include(":system-design-pattern:resilience:timeouts")
include(":system-design-pattern:resilience:graceful-degradation")

// Architectural Patterns (20)
include(":system-design-pattern:architectural:command-query-responsibility-segregation")
include(":system-design-pattern:architectural:event-driven-architecture")
include(":system-design-pattern:architectural:event-sourcing")
include(":system-design-pattern:architectural:flux")
include(":system-design-pattern:architectural:front-controller")
include(":system-design-pattern:architectural:hexagonal-architecture")
include(":system-design-pattern:architectural:intercepting-filter")
include(":system-design-pattern:architectural:layered-architecture")
include(":system-design-pattern:architectural:microservices-aggregator")
include(":system-design-pattern:architectural:model-view-controller")
include(":system-design-pattern:architectural:model-view-intent")
include(":system-design-pattern:architectural:model-view-presenter")
include(":system-design-pattern:architectural:model-view-viewmodel")
include(":system-design-pattern:architectural:naked-objects")
include(":system-design-pattern:architectural:page-controller")
include(":system-design-pattern:architectural:presentation-model")
include(":system-design-pattern:architectural:service-layer")
include(":system-design-pattern:architectural:service-to-worker")
include(":system-design-pattern:architectural:backend-for-frontend")
include(":system-design-pattern:architectural:composable-architecture")

// Messaging Patterns (2)
include(":system-design-pattern:messaging:data-bus")
include(":system-design-pattern:messaging:event-aggregator")

// Data Access Patterns (11)
include(":system-design-pattern:data-access:metadata-mapping")
include(":system-design-pattern:data-access:optimistic-offline-lock")
include(":system-design-pattern:data-access:repository")
include(":system-design-pattern:data-access:serialized-entity")
include(":system-design-pattern:data-access:serialized-lob")
include(":system-design-pattern:data-access:sharding")
include(":system-design-pattern:data-access:single-table-inheritance")
include(":system-design-pattern:data-access:table-module")
include(":system-design-pattern:data-access:transaction-script")
include(":system-design-pattern:data-access:unit-of-work")
include(":system-design-pattern:data-access:version-number")

// Resource Management Patterns (3)
include(":system-design-pattern:resource-management:resource-acquisition-is-initialization")
include(":system-design-pattern:resource-management:server-session")
include(":system-design-pattern:resource-management:throttling")